name = "tg-signaling"
main = "src/worker.js"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[[durable_objects.bindings]]
name = "GAME_SERVER"
class_name = "GameServer"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["GameServer"]

[dev]
port = 8787
